// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Qualitico.Data.Entities;
using Qualitico.WebApi.Data;
using System;

namespace Qualitico.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180415032830_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Qualitico.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("Role");

                    b.Property<int?>("UserSubAdminId");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserSubAdminId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Qualitico.Data.Entities.User", b =>
                {
                    b.HasOne("Qualitico.Data.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserSubAdminId");
                });
#pragma warning restore 612, 618
        }
    }
}
